version: "3"

services:
  server:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - defaultnetwork
    user: $UID:$GID
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile
    volumes:
      - ./app:/app
    networks:
      - defaultnetwork
    user: $UID:$GID

networks:
    defaultnetwork:
        driver: bridge
