version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile
    volumes:
      - ./app:/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - defaultnetwork
    user: $UID:$GID

networks:
    defaultnetwork:
        driver: bridge