name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: agile.geosci.ai ssh deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd app.scienxlab.org
            git pull
            make run
          host: ${{ secrets.HOST }}
          user: matt
          key: ${{ secrets.PRIVATE_KEY }}
          args: "-tt -vvv"
